#!/usr/bin/python3
import os,socket,sys
path=os.environ.get("AIMO_SOCKET_PATH",f"/tmp/aimoos-{os.getuid()}.sock")
connection=socket.socket(socket.AF_UNIX,socket.SOCK_STREAM);connection.connect(path)
connection.sendall(("browser:"+(sys.argv[1] if len(sys.argv)>1 else "http://127.0.0.1:8765/")).encode())
connection.close()
